name: mesa-core20
base: core20
adopt-info: mesa
summary: mesa libraries for core20 snaps
description: |
  A content snap containing the mesa libraries and drivers for core 20

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el
  - build-on: s390x

parts:
  mesa:
    plugin: nil
    override-pull:
      snapcraftctl set-version `LANG=C apt-cache policy libgl1-mesa-dri | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'`
    stage-packages:
      - libgl1-mesa-dri
      - va-driver-all
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/egl/lib
      mv $SNAPCRAFT_PART_INSTALL/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri $SNAPCRAFT_PART_INSTALL/egl
      mv $SNAPCRAFT_PART_INSTALL/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/* $SNAPCRAFT_PART_INSTALL/egl/lib
    prime:
      - egl/lib
      - egl/dri

slots:
  graphics-core20:
    interface: content
    read:
      - egl
